### PR TITLE
Company specialties 

### LINKED ISSUE #8: Create Business Specialties (main-content)
_As a site visitor, I want to know what the business specialties from this company_

> Assigned to `Boam`

### Branch(es)

- [x] Create an issue related to this user story on Github and assign self.
- [x] Add a brach named `specialties`
- [x] After html and css are done, commit
- [x] Adjust `development-strategy.md` for next development, if needed
- [x] Push the changes
- [x] Pull request and merge it on Github

### HTML

- [x] Use section for the content (as shown on the browser/wireframe) explaining the specialties of this services
- [x] Add button to add DuckDuckGo to browser

### CSS

- [x] Add styling on new elements

### PR DESCRIPTION
**Pull request by Boam1994**
I made the short one, there isn't an image
I can do what Evan recommanded but i need the image, i don't know how to get it

### CODE REVIEW

**Comment by harunaltunhr** [comment]
Ok, this part looks good, but I dont remember background color is black? Iam looking from phone. Maybe Yana will look

**Comment by harunaltunhr** [comment]
You can resolve conflicts with Yana

**Review by harunaltunhr — APPROVED** [review]

**Comment by Boam1994** [comment]
The background is black for the two versions ( short & long ones) in my browser

**Comment by adekimpianna** [comment]
I think no matter the `background-colour` is (white or black), we can still change the colour on the final touches, right? The layout seems correct and that is more important. Do you agree? @Boam1994 @harunaltunhr

**Comment by harunaltunhr** [comment]
Black is normal?

**Pull request merged**
